---
# tasks file for f5-bigip

- name: Grab F5 facts
  bigip_device_info:
    provider: "{{ f5_provider }}"
    gather_subset:
      - system-info
      - interfaces 
      - vlans
  register: facts
  tags: facts

- name: Debug facts
  debug: 
    msg: "{{ hostvars[inventory_hostname] }}"
  tags: [never, debug, facts]

- name: Include facts
  include_tasks: facts.yml
  tags: facts

- name: Include licenses
  include_tasks: license.yml
  tags: license

- name: Include load balance
  include_tasks: balance.yml

- include_tasks: postprovision.yml
  tags: [postprovision, prepare]

- include_tasks: balance.yml 
  tags: [balance]

- include_tasks: poolmember.yml
  tags: [poolmember]

- include_tasks: poolreport.yml
  tags: [report]

- include_tasks: 
    file: reverseengineer.yml
    apply: 
      tags: always
  tags: [reverse]

- name: Revoke licenses
  include_tasks: revoke_license.yml
  tags: license
