---

- name: Set state of poolmember
  f5networks.f5_modules.bigip_pool_member:
    provider: "{{ f5_provider }}"
    name: "{{ hostvars[item].inventory_hostname }}"
    host: "{{ hostvars[item].ansible_host }}"
    port: "{{ hostvars[item].port }}"
    state: "{{ input_member_state | default('present') }}"
    pool: "{{ f5_pool | default('www_pool') }}"
  loop: "{{ input_webservers }}"
  tags: [always]
