---
# handlers file for f5-bigip

- name: save config
  bigip_config:
    provider: "{{ f5_provider }}"
    save: yes

- name: restart httpd server 
  service: 
    name: httpd
    enabled: yes
    state: restarted
  become: yes