---

- name: BigIP F5 UCS backup
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - include_vars: ../defaults/main.yml

    - name: Create backup UCS (User Configuration Set)
      f5networks.f5_modules.bigip_ucs_fetch:
        provider: "{{ f5_provider }}"
        backup: yes
        only_create_file: no
        dest: /tmp/cs_backup.ucs
      register: backupinfo

    - name: Debug backup content
      debug:
        var: backupinfo

- name: Store files via scp
  hosts: "{{ backup_server_server }}"
  connection: ssh
  tasks:
    - include_vars: ../defaults/main.yml

    - name: Create backup folder on backup server
      ansible.builtin.file:
        path: "{{ backup_server_folder }}"
        state: directory
      become: true

    - name: Copy config to backup server
      copy:
        src: "/tmp/cs_backup.ucs"
        dest: "{{ backup_server_folder }}backup-f5-{{ '%Y-%m-%dT%H:%M:%S' | strftime(ansible_date_time.epoch) }}"
      become: true


