---

- name: BigIP F5 provisioning
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
    - include_vars: ../defaults/main.yml
    #- include_vars: ../vaults/f5_vault.yml

    - include_tasks: ../tasks/poolmember.yml

  handlers:
    - import_tasks: ../handlers/main.yml