---

- name: BigIP F5 read
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - include_vars: ../defaults/main.yml

    - include_tasks: ../tasks/poolreport_read.yml

  handlers:
    - import_tasks: ../handlers/main.yml
